name: Multiple Curl Requests

on:
  schedule:
    - cron: '*/10 * * * *'  # 每隔 10 分钟执行一次
  workflow_dispatch:

jobs:
  curl-requests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Curl SIGN_SERVER
      run: curl ${{ secrets.SIGN_SERVER }}
      
    - name: Curl GPT_API
      run: curl ${{ secrets.GPT_API }}

    # Add more curl requests as needed
